language: python3
python:
- "3.6"
os:
- linux
sudo: required
services:
  - docker
install:
- sudo pip install -r requirements.txt
script:
- ./update.py $COMBO
env:
- "COMBO=python:2 node:6"
- "COMBO=python:2 node:8"
