language: python
python:
- "3.7"
os:
- linux
sudo: required
services:
  - docker
install:
- pip install -r requirements.txt
script:
- travis_retry python update.py `[ $TRAVIS_BRANCH == master ] && echo --push` $C
env:
- C="python:3 node:14"
- C="python:3 node:12"
- C="python:3 node:10"
- C="python:3.6 node:14"
- C="python:3.6 node:12"
- C="python:3.6 node:10"
- C="python:3.7 node:14"
- C="python:3.7 node:12"
- C="python:3.7 node:10"
- C="python:3.8 node:14"
- C="python:3.8 node:12"
- C="python:3.8 node:10"
- C="ruby:2 node:14"
- C="ruby:2 node:12"
- C="ruby:2 node:10"
- C="ruby:2.5 node:14"
- C="ruby:2.5 node:12"
- C="ruby:2.5 node:10"
- C="ruby:2.6 node:14"
- C="ruby:2.6 node:12"
- C="ruby:2.6 node:10"
- C="java:7-jdk node:10 python:3.6 --override-env JAVA_DEBIAN_VERSION=7u261-2.6.22-1~deb8u1 --override-from buildpack-deps:jessie"
- C="openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:10 python:3.6 --override-from buildpack-deps:buster"
- C="openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:12 python:3.6 --override-from buildpack-deps:buster"
