language: python3
python:
- "3.6"
os:
- linux
sudo: required
services:
  - docker
install:
- sudo python3 -m pip install -r requirements.txt
script:
- ./update.py $I1 $I2
env:
- "I1=python:2 I2=node:6"
- "I1=python:2 I2=node:8"
