name: combos/python_node:3_16

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        combo:
        - python:3 node:16
        platform:
        - linux/arm/v7
        - linux/arm64/v8
        - linux/amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Python requirements
      run: |
        poetry install

    - name: Build
      run: |
        poetry run python update.py `[ ${GITHUB_REF##*/} == master ] && echo --push` ${{ matrix.combos }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Image digests
      run: |
        # print digests for easy verification
        docker images --no-trunc
  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Create and push manifest images
      uses: Noelware/docker-manifest-action@191bad46d87f7a70c8a82054d4cf98ee8b942dca
      with:
        base-image: combos/python_node:3_16
        extra-images: combos/python_node:3_16-linux_arm_v7,combos/python_node:3_16-linux_arm64_v8,combos/python_node:3_16-linux_amd64
        push: true
