name: Build Images Daily
'on':
  push: {}
  pull_request: {}
  workflow_dispatch:
    inputs:
      forceUpdate:
        description: Build new images even if base images have not updated
        required: true
        default: false
        type: boolean
  schedule:
    cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        combo:
        - python:3 node:16
        platform:
        - linux/arm/v7
        - linux/arm64/v8
        - linux/amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      run: '|

        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

        echo "$HOME/.poetry/bin" >> $GITHUB_PATH'
    - name: Python Requirements
      run: '|

        poetry install'
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      with:
        install: true
    - name: Build
      run: poetry run python update.py `[ ${GITHUB_REF##*/} == master ] && echo --push` ${{ matrix.combo }} --platform ${{ matrix.platform }} ${{ inputs.forceUpdate && '--force-update' || '' }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Image digests
      run: docker images --no-trunc
  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Create and push manifest images
      uses: Noelware/docker-manifest-action@191bad46d87f7a70c8a82054d4cf98ee8b942dca
      with:
        base-image: combos/python_node:3_16
        extra-images: combos/python_node:3_16-linux_arm_v7,combos/python_node:3_16-linux_arm64_v8,combos/python_node:3_16-linux_amd64
        push: true
