name: Build Images Daily

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      forceUpdate:
        description: 'Build new images even if base images have not updated'
        required: true
        default: false
        type: boolean
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        combos:
          - python:3 node:16
          - python:3 node:14
          - python:3.7 node:16
          - python:3.7 node:14
          - python:3.8 node:16
          - python:3.8 node:14
          - python:3.9 node:16
          - python:3.9 node:14
          - python:3.10 node:16
          - python:3.10 node:14
          - python:3.10-slim-bullseye node:16-bullseye-slim
          - ruby:2 node:16
          - ruby:2 node:14
          - ruby:2.7 node:16
          - ruby:2.7 node:14
          - ruby:3 node:16
          - ruby:3 node:14
          - openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:14 python:3.7 --override-from buildpack-deps:buster
          - openjdk:11@https://raw.githubusercontent.com/docker-library/openjdk/master/11/jdk/buster/Dockerfile node:14
        platform:
          - linux/amd64
          - linux/arm32/v6
          - linux/arm32/v7
          - linux/arm64/v8
        exclude:
          - combos: openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:14 python:3.7 --override-from buildpack-deps:buster
            platform: linux/arm32/v6
          - combos: openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:14 python:3.7 --override-from buildpack-deps:buster
            platform: linux/arm32/v7
          - combos: openjdk:11@https://raw.githubusercontent.com/docker-library/openjdk/master/11/jdk/buster/Dockerfile node:14
            platform: linux/arm32/v6
          - combos: openjdk:11@https://raw.githubusercontent.com/docker-library/openjdk/master/11/jdk/buster/Dockerfile node:14
            platform: linux/arm32/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Python requirements
        run: |
          poetry install

      - name: Build
        run: |
          poetry run python update.py `[ ${GITHUB_REF##*/} == master ] && echo --push` ${{ matrix.combos }} --platform ${{ matrix.platform }} ${{ inputs.forceUpdate && '--force-update' || '' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image digests
        run: |
          # print digests for easy verification
          docker images --no-trunc
