name: Build Images Daily

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        combos:
          - python:3 node:14
          - python:3 node:12
          - python:3 node:10
          - python:3.6 node:14
          - python:3.6 node:12
          - python:3.6 node:10
          - python:3.7 node:14
          - python:3.7 node:12
          - python:3.7 node:10
          - python:3.8 node:14
          - python:3.8 node:12
          - python:3.8 node:10
          - ruby:2 node:14
          - ruby:2 node:12
          - ruby:2 node:10
          - ruby:2.5 node:14
          - ruby:2.5 node:12
          - ruby:2.5 node:10
          - ruby:2.6 node:14
          - ruby:2.6 node:12
          - ruby:2.6 node:10
          - java:7-jdk node:10 python:3.6 --override-env JAVA_DEBIAN_VERSION=7u261-2.6.22-1~deb8u1 --override-from buildpack-deps:jessie
          - openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:10 python:3.6 --override-from buildpack-deps:buster
          - openjdk:8-jdk@https://raw.githubusercontent.com/docker-library/openjdk/master/8/jdk/buster/Dockerfile node:12 python:3.6 --override-from buildpack-deps:buster

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          python update.py `[ ${GITHUB_REF##*/} == master ] && echo --push` ${{ matrix.combos }}
