name: Build Images Daily

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        combos:
          - ruby:3 node:14

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Login to DockerHub locally
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}    

      - name: Python requirements
        run: |
          pip install -r requirements.txt

      - name: Build
        run: |
          python update.py --push ${{ matrix.combos }}

      - name: Image digests
        run: |
          # print digests for easy verification
          docker images --no-trunc
