name: Build Images Daily
#TODO: Delete this file
on:
  workflow_dispatch:
    inputs:
      forceUpdate:
        description: 'Build new images even if base images have not updated'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        combos:
        platform:

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Python requirements
        run: |
          poetry install

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
        with:
          install: true

      - name: Build
        run: |
          poetry run python update.py `[ ${GITHUB_REF##*/} == master ] && echo --push` ${{ matrix.combos }} --platform ${{ matrix.platform }} ${{ inputs.forceUpdate && '--force-update' || '' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image digests
        run: |
          # print digests for easy verification
          docker images --no-trunc