name: Build Images Daily

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      forceUpdate:
        description: 'Build new images even if base images have not updated'
        required: true
        default: false
        type: boolean
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - combos: openjdk:11@https://raw.githubusercontent.com/docker-library/openjdk/master/11/jdk/buster/Dockerfile node:14
            platform: linux/amd64,linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Python requirements
        run: |
          poetry install

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build
        run: |
          poetry run python update.py `[ ${GITHUB_REF##*/} == master ] && echo --push` ${{ matrix.combos }} --platform ${{ matrix.platform }} --force-update
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image digests
        run: |
          # print digests for easy verification
          docker images --no-trunc